
# these labels will be applied to all releases in a Helmfile. Useful in templating if you have a helmfile per environment or customer and don't want to copy the same label to each release
commonLabels:
  cluster: big-kube-flatcar

helmfiles:
- path: helmfiles/debug/helmfile.yaml
  
# - path: git::https://github.com/cloudposse/helmfiles.git@releases/kiam.yaml?ref=0.40.0

bases:
- defaults.yaml

environments:
  local:
    values:
    - environments/local.yaml