apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name echo-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: debug
  source:
    repoURL: https://ealenn.github.io/charts
    targetRevision: '0.5.0'
    chart: *name
    helm:
      values: | 
        {{- $.Files.Get "values/echo-server.yaml" | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: *name
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false